version: '3.7'
services:
  backend:
    build: './backend'
    env_file: "./.env"
    ports:
      - '4001:4001'
    networks:
      - exam-network
    depends_on:
      - mysql
    volumes:
      - './backend/:/app/src'

  mysql:
    image: mysql
    env_file: './.env'
    networks:
      - exam-network
    volumes:
      - 'db-data:/var/lib/mysql'

  frontend:
    build: './frontend'
    ports:
      - '4000:3000'
    networks:
      - exam-network


networks:
  exam-network:


volumes:
  db-data: